"""UI primitives — low-level reusable components for consistent styling.

These replace inline style={} blocks with typed, composable functions.
All primitives pull from the shared theme tokens in ui.theme.

Organization:
    box.py       — Surface, card, overlay, icon container, navbar, modal primitives
    text.py      — Heading, body, label, muted, accent, truncated text presets
    button.py    — Primary, ghost, secondary, pill, chip, period toggle buttons
    input.py     — Text input, search input, select, textarea, form field presets
    layout.py    — VStack, HStack, grid, scroll area, spacer, divider presets
    feedback.py  — Skeleton, spinner, empty state feedback primitives
"""

from ourportfolios.ui.primitives.box import (
    chart_box,
    dropdown_panel,
    glass_box,
    glow_orb,
    icon_container,
    list_row,
    metric_box,
    modal_panel,
    navbar_bar,
    overlay_box,
    section_container,
    subtle_box,
    surface_box,
    user_avatar,
)
from ourportfolios.ui.primitives.button import (
    accent_link,
    chip_button,
    compare_button,
    filter_button,
    ghost_button,
    ghost_button_sm,
    ghost_button_xs,
    icon_button,
    icon_button_xs,
    locked_link,
    nav_link,
    period_button,
    pill_button,
    pill_toggle,
    primary_button,
    primary_button_sm,
    secondary_button,
    toggle_button,
)
from ourportfolios.ui.primitives.feedback import (
    empty_state,
    loading_spinner,
    skeleton_box,
    skeleton_circle,
    skeleton_text,
)
from ourportfolios.ui.primitives.input import (
    form_field,
    search_icon,
    search_input,
    search_input_with_icon,
    select_input,
    text_area_input,
    text_input,
)
from ourportfolios.ui.primitives.layout import (
    absolute_fill,
    centered_container,
    content_stack,
    divider,
    divider_vertical,
    flex_col,
    flex_row,
    grid_cols,
    hstack,
    inline_cluster,
    page_container,
    scroll_area_both,
    scroll_area_h,
    scroll_area_v,
    section_stack,
    spacer,
    toolbar_row,
    vstack,
)
from ourportfolios.ui.primitives.text import (
    accent_text,
    badge_text,
    body_text,
    heading,
    label_text,
    muted_text,
    nav_link_text,
    subheading,
    truncated_text,
)

__all__ = [
    "absolute_fill",
    "accent_link",
    "accent_text",
    "badge_text",
    "body_text",
    "centered_container",
    "chart_box",
    "chip_button",
    "compare_button",
    "content_stack",
    "divider",
    "divider_vertical",
    "dropdown_panel",
    "empty_state",
    "filter_button",
    "flex_col",
    "flex_row",
    "form_field",
    "ghost_button",
    "ghost_button_sm",
    "ghost_button_xs",
    "glass_box",
    "glow_orb",
    "grid_cols",
    "heading",
    "hstack",
    "icon_button",
    "icon_button_xs",
    "icon_container",
    "inline_cluster",
    "label_text",
    "list_row",
    "loading_spinner",
    "locked_link",
    "metric_box",
    "modal_panel",
    "muted_text",
    "nav_link",
    "nav_link_text",
    "navbar_bar",
    "overlay_box",
    "page_container",
    "period_button",
    "pill_button",
    "pill_toggle",
    "primary_button",
    "primary_button_sm",
    "scroll_area_both",
    "scroll_area_h",
    "scroll_area_v",
    "search_icon",
    "search_input",
    "search_input_with_icon",
    "secondary_button",
    "section_container",
    "section_stack",
    "select_input",
    "skeleton_box",
    "skeleton_circle",
    "skeleton_text",
    "spacer",
    "subheading",
    "subtle_box",
    "surface_box",
    "text_area_input",
    "text_input",
    "toggle_button",
    "toolbar_row",
    "truncated_text",
    "user_avatar",
    "vstack",
]
