"""empty message

Revision ID: 0c5f2521ec3d
Revises: b79536310b3b
Create Date: 2026-04-17 16:07:28.431137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0c5f2521ec3d'
down_revision: Union[str, Sequence[str], None] = 'b79536310b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overview_df')
    op.drop_table('vnindex')
    op.drop_table('stats_df')
    op.drop_table('frameworks_df')
    op.drop_table('framework_metrics_df')
    op.drop_table('profile_df')
    op.drop_table('price_df')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_df',
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('pct_price_change', sa.FLOAT(), nullable=True),
    sa.Column('accumulated_volume', sa.FLOAT(), nullable=True),
    sa.Column('current_price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('profile_df',
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('framework_metrics_df',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('metrics', sqlite.JSON(), nullable=False),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.Column('framework_uuid', sa.NUMERIC(), nullable=False),
    sa.ForeignKeyConstraint(['framework_uuid'], ['frameworks_df.framework_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frameworks_df',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('author', sa.TEXT(), nullable=True),
    sa.Column('complexity', sa.TEXT(), nullable=True),
    sa.Column('scope', sa.TEXT(), nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('source_url', sa.TEXT(), nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), nullable=True),
    sa.Column('metrics', sqlite.JSON(), nullable=True),
    sa.Column('framework_id', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework_id')
    )
    op.create_table('stats_df',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=True),
    sa.Column('roe', sa.FLOAT(), nullable=True),
    sa.Column('roa', sa.FLOAT(), nullable=True),
    sa.Column('ev_ebitda', sa.FLOAT(), nullable=True),
    sa.Column('dividend_yield', sa.FLOAT(), nullable=True),
    sa.Column('gross_margin', sa.FLOAT(), nullable=True),
    sa.Column('net_margin', sa.FLOAT(), nullable=True),
    sa.Column('doe', sa.FLOAT(), nullable=True),
    sa.Column('alpha', sa.FLOAT(), nullable=True),
    sa.Column('beta', sa.FLOAT(), nullable=True),
    sa.Column('pe', sa.FLOAT(), nullable=True),
    sa.Column('pb', sa.FLOAT(), nullable=True),
    sa.Column('eps', sa.BIGINT(), nullable=True),
    sa.Column('ps', sa.FLOAT(), nullable=True),
    sa.Column('ev', sa.FLOAT(), nullable=True),
    sa.Column('rsi14', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vnindex',
    sa.Column('time', sa.DATETIME(), nullable=False),
    sa.Column('close', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('time')
    )
    op.create_table('overview_df',
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('industry', sa.VARCHAR(), nullable=True),
    sa.Column('market_cap', sa.FLOAT(), nullable=True),
    sa.Column('exchange', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###
