"""initial schema.

Revision ID: b79536310b3b
Revises:
Create Date: 2026-04-16 21:52:25.042486

"""

from collections.abc import Sequence
from importlib import import_module

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

op = import_module("alembic.op")

# revision identifiers, used by Alembic.
revision: str = "b79536310b3b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frameworks_df",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("complexity", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("framework_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("framework_id"),
        schema="frameworks",
    )
    op.create_table(
        "vnindex",
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("close", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("time"),
        schema="market",
    )
    op.create_table(
        "overview_df",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
        schema="tickers",
    )
    op.create_table(
        "price_df",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("pct_price_change", sa.Float(), nullable=True),
        sa.Column("accumulated_volume", sa.Float(), nullable=True),
        sa.Column("current_price", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
        schema="tickers",
    )
    op.create_table(
        "profile_df",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
        schema="tickers",
    )
    op.create_table(
        "stats_df",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("roe", sa.Float(), nullable=True),
        sa.Column("roa", sa.Float(), nullable=True),
        sa.Column("ev_ebitda", sa.Float(), nullable=True),
        sa.Column("dividend_yield", sa.Float(), nullable=True),
        sa.Column("gross_margin", sa.Float(), nullable=True),
        sa.Column("net_margin", sa.Float(), nullable=True),
        sa.Column("doe", sa.Float(), nullable=True),
        sa.Column("alpha", sa.Float(), nullable=True),
        sa.Column("beta", sa.Float(), nullable=True),
        sa.Column("pe", sa.Float(), nullable=True),
        sa.Column("pb", sa.Float(), nullable=True),
        sa.Column("eps", sa.BigInteger(), nullable=True),
        sa.Column("ps", sa.Float(), nullable=True),
        sa.Column("ev", sa.Float(), nullable=True),
        sa.Column("rsi14", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="tickers",
    )
    op.create_table(
        "framework_metrics_df",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("metrics", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("framework_uuid", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["framework_uuid"],
            ["frameworks.frameworks_df.framework_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="frameworks",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("framework_metrics_df", schema="frameworks")
    op.drop_table("stats_df", schema="tickers")
    op.drop_table("profile_df", schema="tickers")
    op.drop_table("price_df", schema="tickers")
    op.drop_table("overview_df", schema="tickers")
    op.drop_table("vnindex", schema="market")
    op.drop_table("frameworks_df", schema="frameworks")
    # ### end Alembic commands ###
